import { FlashType } from './constants';

export const getData = (flashType: FlashType) => {
    switch (flashType) {
        case 'Binomial':
            return BinomialData.map(d => [d[0], d[1].split(','), d[2]]);
        case 'Nutrient':
            return NutrientData;
        default:
            return GlossaryData;
    }
};

const NutrientData = [
    [
        'Nitrogen',
        'Mobile',
        'Chlorophyll, protein synthesis, amino acids, healthy growth of stems and leaves',
        'poor new growth, leaf yellowing from middle outwards, fewer and smaller fruit, stunted growth',
    ],
    [
        'Phosphorous',
        'Partially mobile',
        'protein synthesis, ATP, cell membrane, root growth, cell division, meristem tissues, protein formation, respiration',
        'purple or reddish leaf discoloration, poor growth, poor roots, early fruit drop',
    ],
    [
        'Potassium',
        'Mobile',
        'Regulates water loss, flower growth, fruit and seed development, respiration and transpiration, accumulates in vacuole, thickens cell walls',
        'Yellow leaf margins and veins, leaf roll and crinkle, lowered hardiness',
    ],
    [
        'Calcium',
        'Immobile',
        'Cell wall formation',
        'Yellow new growth, tissue death',
    ],
    [
        'Magnesium',
        'Mobile',
        'Key component of chlorophyll, mobility of phosphorous, abundant in clay, inhibited b high potassium or calcium',
        'Interveinal chlorosis',
    ],
    [
        'Sulphur',
        'Mobile',
        'proteins, enzymes, vitamins, chlorophyll',
        'overall yellowing, dying tips, narrow leaves, stunted growth',
    ],
    [
        'Boron',
        'Immobile',
        'Seed and fruit formation, sugar transport',
        'stunted tips, organ deformity',
    ],
    [
        'Iron',
        'Immobile',
        'Chlorophll and enzyme production',
        'yellow new growth, ivory coloured leaves in severe cases',
    ],
    ['Copper', 'Immobile', 'metbolism', 'pale green new growth'],
    [
        'Manganese',
        'Immobile',
        'photosynthesis and respiration',
        'interveinal chlorosis on new growth',
    ],
    [
        'Zinc',
        'Immobile',
        'enzyme production',
        'interveinal chlorosis on new growth',
    ],
    [
        'Molybdenum',
        'Immobile',
        'Nitrogen cycle',
        'yellow leaf margins on new growth',
    ],
];

const GlossaryData = [
    [
        'petiole',
        'Where it is present in a plant, it attaches the leaf blade (lamina) of some plants to a stem',
    ],
    [
        'axillary bud',
        'Forming in the axil join between leaf and stem, a form of lateral bud and can develop into stem and flower shoots',
    ],
    [
        'perrenation',
        'The storage of food within a plant structure (eg tuber, corm, rhizome) to allow the plant to survive from one season to another (eg overwintering)',
    ],
    [
        'respiration',
        'Process that utilises complex carbohydrates, most commonly in the presence of oxygen, to release energy (ATP) with water vapour and carbon dioxide as waste products (and ethanol if anaerobic)',
    ],
    ['biotic impact', 'pest and disease disorders'],
    ['abiotic impact', 'non-living disorders. eg environment, nutrition'],
    ['rose balling', 'wet flowers failing to open'],
    [
        'frost damage',
        'distortion or blackening of flowers, buds, shoots, leaves.  cracked cambium',
    ],
    ['frost lift (heave)', 'root lift due to frost-thaw cycles'],
    [
        'advection',
        'the transference of heat energy in a horizontal stream of gas, esp of air',
    ],
    [
        'blossom end rot',
        'lack of calcium uptake due to inconsistent water supply (tomatoes)',
    ],
    [
        'bitter pit',
        'lack of calcium uptake due to inconsistent water supply (apples)',
    ],
    ['etiolated', 'grown in absence of light.  lacking chlorophyll'],
    ['pneumatophores', 'snorkel roots to enable air (oxygen) intake'],
    [
        'fasciation',
        'seemingly random mutations resulting in bands, bundles, flattening, fusing',
    ],
    ['tetraploid', '4 sets of chromosomes instead of usual 2'],
    ['coppicing', 'continual harvest of young shoots at ground level'],
    [
        'pollarding',
        'continual harvest of young shoots at a level above grazing',
    ],
    [
        'nitrogen fixing',
        'micro organisms produce nitrate or ammonia from gaseous nitrogen',
    ],
    [
        'adsorption',
        'adhesion of atoms, ions or molecules from a gas, liquid or dissolved solid to a surface',
    ],
    [
        'colloid',
        'any substance consisting of particles substantially larger than atoms or ordinary molecules but too small to be visible to the unaided eye',
    ],
];

const BinomialData = [
    ['Vinca minor', 'lesser periwinkle,dwarf periwinkle', ''],
    [
        'Vinca major',
        'bigleaf periwinkle,large periwinkle,greater periwinkle,blue periwinkle',
        '',
    ],
    ['Digitalis purpurea', 'common foxglove', 'raceme inflorescence'],
    ['Campanula rotundifolia', 'common harebell', ''],
    ['Betula utilis ssp. jacquemonti', 'west himalayan birch', ''],
    ['Rosa chinensis', 'china rose,chinese rose,bengal rose', ''],
    ['Brassica oleracea var. italica', 'broccoli', ''],
    ['Lamium orvala', 'balm-leaved red deadnettle', ''],
    [
        'Achillea millefolium',
        'common yarrow',
        'full sun,chop to ground in autumn,divide in spring',
    ],
    ['Cucumis sativus', 'cucumber', ''],
    ['Tagetes patula', 'french marigold', ''],
    ['Ginkgo biloba', 'maidenhair tree', ''],
    ['Quercus robur', 'common oak', 'alternate leaves'],
    ['Rudbeckia hirta', 'black-eyed susan', ''],
    ['Cirsium arvense', 'creeping thistle', 'controlled under weeds act'],
    [
        'Fallopia japonica',
        'japanese knotweed',
        'controlled under weeds act,asbo',
    ],
    [
        'Acanthus mollis',
        "common bear's breech,bear's breeches",
        'hard to eradicate,remove stems after flowering,divide in autumn,spike inflorescence',
    ],
    ['Marchantia polymorpha', 'liverwort', ''],
    ['Equisetum arvense', 'common horsetail', 'spreads easily'],
    ['Sequoia gigantea', 'giant redwood', ''],
    ['Cycas revoluta', 'japanese sago plant', ''],
    ['Phalaenopsis schilleriana', "schiller's moth orchid", ''],
    ['Phaseolus vulgaris', 'common bean,french bean', ''],
    ['Fritillaria meleagris', "snake's head fritillary,chequered lily", ''],
    ['Magnolia grandiflora', 'evergreen magnolia,large-flowered magnolia', ''],
    ['Hosta plantaginea', 'fragrant plantain lily', ''],
    ['Rosa gallica', 'gallic rose,french rose,rose of provins', ''],
    ['Hedera helix', 'common ivy', ''],
    ['Senecio vulgaris', 'birdseed,groundsel', 'suffers from rust'],
    ['Stellaria media', 'common chickweed', ''],
    ['Cardamine hirsuta', "hairy bittercress,lamb's cress", 'ephemeral'],
    [
        'Fagus sylvatica',
        'common beech,european beech',
        'deep roots,drought tolerant',
    ],
    ['Capsella bursa-pastoris', "shepard's purse,witches pouches", 'ephemeral'],
    ['Calendula officinalis', 'common marigold,pot marigold', ''],
    ['Nigella damascena', 'love-in-a-mist', ''],
    ['Lamium purpurea', 'french nettle,red deadnettle', ''],
    ['Euphorbia helioscopa', "sun spurge,cat's milk", ''],
    ['Matricaria perforata', 'false chamomile', ''],
    ['Sonchus asper', 'prickly sowthistle', ''],
    ['Alcea rosea', 'hollyhock', ''],
    ['Dianthus barbatus', 'sweet william', ''],
    ['Daucus carota', 'wild carrot', ''],
    ['Beta vulgaris', 'common beet', ''],
    ['Dipsacus fullonum', "common teasel,barber's brushes", ''],
    ['Erysimum cheiri', 'common wallflower,bleeding heart', ''],
    [
        'Senecio jacobaea',
        "common ragwort,ragweed,stinking willy,st james's wort",
        'controlled under weeds act',
    ],
    ['Cirsium vulgare', 'spear thistle', 'controlled under weeds act'],
    ['Arctium minus', 'lesser burdock', ''],
    [
        'Taraxacum officianale',
        'dandelion,pee in the bed',
        'parachute seed head',
    ],
    ['Rubus fruticosus', 'blackberry,bramble', ''],
    ['Fraxinus excelsior', 'common ash', 'pinnate leaves,opposite leaves'],
    ['Acer pseudoplatanus', 'sycamore', 'palmate leaves'],
    ['Eschscholzia californica', 'californian poppy', ''],
    ['Centaurea cyanus', 'cornflower', ''],
    ['Lathyrus odoratus', 'sweet pea', ''],
    ['Limnanthes douglasii', 'poached-egg plant', ''],
    ['Cucurbita pepo', 'marrow pumpkin,marrow,courgette', ''],
    ['Ageratum altissimum', 'white snakeroot', ''],
    ["Cosmos bipinnatus 'Daydream'", 'cosmea daydream', 'half-hardy'],
    ['Coleus scutellarioides', 'painted nettle', ''],
    ['Myrtus communis', 'common myrtle', ''],
    ['Prunus laurocerasus', 'cherry laurel', ''],
    ['Philadelphus coronarius', 'common mock orange', ''],
    ['Berberis thunbergii', 'japanese barberry', 'alternate leaves'],
    ['Euonymus japonicus', 'evergreen spindle', ''],
    ['Pinus sylvestris', 'scots pine', ''],
    ['Cotoneaster bullatus', 'hollyberry cotoneaster', ''],
    ['Allium giganteum', 'giant onion', 'umbel inflorescence'],
    [
        'Coriandrum sativum',
        'coriander,chinese parsley,cilantro',
        'compound umbel inflorescence',
    ],
    ['Sambucus nigra', 'common elder', 'corymb inflorescence'],
    ['Myosotis sylvatica', 'garden forget-me-not', 'cyme inflorescence'],
    ['Syringa vulgaris', 'common lilac', 'panicle inflorescence'],
    ['Helianthus annuus', 'common sunflower', 'capitulum inflorescence'],
    ['Phlomis fruticosa', 'jerusalem sage', 'verticalister inflorescence'],
    ['Pisum sativum', 'garden pea', 'legume seed head'],
    ['Papaver somniferum', 'opium poppy', 'capsule seed head'],
    [
        'Aquilegia vulgaris',
        "common columbine,granny's bonnets",
        'follicle seed head',
    ],
    [
        'Acer campestre',
        'field maple',
        'winged capsule seed head,palmate leaves,opposite leaves',
    ],
    ['Juglans regia', 'common walnut', 'pinnate leaves'],
    ['Sorbus acuparia', 'rowan,mountain ash', 'pinnate leaves'],
    ['Aesculus hippocastanum', 'horse chestnut', ''],
    ['Enkianthus campanulatus', 'redvein enkianthus', 'whorled leaves'],
    ['Solanum tuberosum', 'potato', ''],
    ['Solanum lycopersicum', 'tomato', ''],
    ['Lavandula augustifolia', 'english lavender,common lavender', ''],
    ['Sequoia sempervirens', 'coastal redwood', 'tallest living tree'],
    ['Euphorbia lathyris', 'caper spurge,mole plant', ''],
    ['Coleus caninus', 'scat,scaredy cat', ''],
    ['Sedum rosea', 'dark purple stonecrop,roseroot', ''],
    ['Betula nigra', 'black birch', 'waterlogged tolerant'],
    [
        'Armeria maritima',
        "thrift,lady's cushion",
        'full sun,drought resistant,low growing,wind tolerant',
    ],
    ["Salix udensis 'Sekka'", 'fantail willow', 'full sun'],
    ['Acer platanoides', 'Norway maple', ''],
    ['Ochroma pyramidale', 'Balsa tree', ''],
    [
        'Cardamine pratensis',
        'cuckoo flower',
        'Liked by orange-tipped butterfly',
    ],
    ['Echinacea purpurea', 'purple coneflower', 'full sun,partial shade'],
    [
        'Symphytum officinale',
        'common comfrey',
        'full sun,partial shade,potassium source',
    ],
    ['Euonymus europaeus', 'spindle', 'aphis egg host'],
    ['Rumex crispus', 'curled dock,yellow dock', 'controlled under weeds act'],
    [
        'Rumex obtusifolius',
        'broad-leaved dock,bitter dock',
        'controlled under weeds act',
    ],
];
