export const data = [
  ["Vinca minor", "lesser periwinkle,dwarf periwinkle"],
  [
    "Vinca major",
    "bigleaf periwinkle,large periwinkle,greater periwinkle,blue periwinkle"
  ],
  ["Digitalis purpurea", "common foxglove"],
  ["Campanula rotundifolia", "common harebell"],
  ["Betula utilis ssp. jacquemonti", "west himalayan birch"],
  ["Rosa chinensis", "china rose,chinese rose,bengal rose"],
  ["Brassica oleracea var. italica", "broccoli"],
  ["Lamium orvala", "balm-leaved red deadnettle"],
  ["Achillea millefolium", "common yarrow"],
  ["Cucumis sativus", "cucumber"],
  ["Tagetes patula", "french marigold"],
  ["Ginkgo biloba", "maidenhair tree"],
  ["Quercus robur", "common oak"],
  ["Rudbeckia hirta", "black-eyed susan"],
  ["Rudbeckia hirta var. pulcherrima", "black-eyed susan"],
  ["Rudbeckia hirta 'Denver Daisy'", "black-eyed susan"],
  ["Acanthus mollis", "common bear's breech,bear's breeches"],
  ["Marchantia polymorpha", "liverwort"],
  ["Equisetum arvense", "common horsetail"],
  ["Sequoia gigantea", "giant redwood"],
  ["Cycas revoluta", "japanese sago plant"],
  ["Phalaenopsis schilleriana", "schiller's moth orchid"],
  ["Phaseolus vulgaris", "common bean,french bean"],
  ["Fritillaria  meleagris", "snake's head fritillary,chequered lily"],
  ["Magnolia grandiflora", "evergreen magnolia,large-flowered magnolia"],
  ["Hosta plantaginea", "fragrant plantain lily"],
  ["Rosa gallica", "gallic rose,french rose,rose of provins"],
  ["Hedera helix", "common ivy"],
  ["Senecio vulgaris", "birdseed,groundsel"],
  ["Stellaria media", "common chickweed"],
  ["Cardamine hirsuta", "hairy bittercress,lamb's cress"],
  ["Fagus sylvatica", "common beech"],
  ["Capsella bursa-pastoris", "shepard's purse,witches pouches"],
  ["Calendula officinalis", "common marigold,pot marigold"],
  ["Nigella damascena", "love-in-a-mist"],
  ["Lamium purpurea", "french nettle,red deadnettle"],
  ["Euphorbia helioscopa", "sun spurge,cat's milk"],
  ["Matricaria perforata", "false chamomile"],
  ["Sonchus asper", "prickly sowthistle"],
  ["Alcea rosea", "hollyhock"],
  ["Dianthus barbatus", "sweet william"],
  ["Daucus carota", "wild carrot"],
  ["Beta vulgaris", "common beet"],
  ["Dipsacus fullonum", "common teasel,barber's brushes"],
  ["Erysimum cheiri", "common wallflower,bleeding heart"],
  [
    "Senecio jacobaea",
    "common ragwort,binweed,ragweed,stinking willy,st james's wort"
  ],
  ["Circium vulagre", "spear thistle"],
  ["Arctium minus", "lesser burdock"],
  ["Taraxacum officianales", "dandelion,pee in the bed"],
  ["Rubus fruticosus", "blackberry,bramble"],
  ["Fraxinus excelsior", "common ash"],
  ["Acer pseudoplatanus", "sycamore"],
  ["Eschscholzia californica", "californian poppy"],
  ["Centaurea cyanus", "cornflower"],
  ["Lathyrus odoratus", "sweet pea"],
  ["Limnanthes douglasii", "poached-egg plant"],
  ["Cucurbita pepo", "marrow pumpkin,marrow,courgette"],
  ["Ageratum altissimum", "white snakeroot"],
  ["Cosmos bipinnatus 'Daydream'", "cosmea daydream"],
  ["Coleus scutellarioides", "painted nettle"],
  ["Myrtus communis", "common myrtle"],
  ["Prunus laurocerasus", "cherry laurel"],
  ["Philadelphus coronarius", "common mock orange"],
  ["Berberis thunbergii", "japanese barberry"],
  ["Euonymous japonicus", "evergreen spindle"],
  ["Pinus sylvestris", "scots pine"],
  ["Cotoneaster bullatus", "hollyberry cotoneaster"],
  ["Allium giganteum", "giant onion"],
  ["Coriandrum sativum", "coriander,chinese parsley,cilantro"],
  ["Sambucus negra", "common elder"],
  ["Myosotis sylvatica", "garden forget-me-not"],
  ["Syringa vulgaris", "common lilac"],
  ["Helianthus annuus", "common sunflower"],
  ["Phlomis fruiticosa", "jerusalem sage"],
  ["Pisum sativum", "garden pea"],
  ["papaver somniforum", "opium poppy"],
  ["Aquelegia vulgaris", "common columbine,granny's bonnets"],
  ["Acer campestre", "field maple"],
  ["Juglans regia", "common walnut"],
  ["Sorbus acuparia", "rowan,mountain ash"],
  ["Aesculus hippocastanum", "horse chestnut"],
  ["Enkianthus campanulatus", "redvein enkianthus"]
]
