export const getData = () => data.map(d => [d[0], d[1].split(','), d[2]]);

const data = [
  ["Vinca minor", "lesser periwinkle,dwarf periwinkle", "NULL"],
    [
      "Vinca major",
      "bigleaf periwinkle,large periwinkle,greater periwinkle,blue periwinkle",
      "NULL"
    ],
    ["Digitalis purpurea", "common foxglove", "NULL"],
    ["Campanula rotundifolia", "common harebell", "NULL"],
    ["Betula utilis ssp. jacquemonti", "west himalayan birch", "NULL"],
    ["Rosa chinensis", "china rose,chinese rose,bengal rose", "NULL"],
    ["Brassica oleracea var. italica", "broccoli", "NULL"],
    ["Lamium orvala", "balm-leaved red deadnettle", "NULL"],
    ["Achillea millefolium", "common yarrow", "NULL"],
    ["Cucumis sativus", "cucumber", "NULL"],
    ["Tagetes patula", "french marigold", "Tagetes_patula.jpg"],
    ["Ginkgo biloba", "maidenhair tree", "Ginkgo_biloba.jpg"],
    ["Quercus robur", "common oak", "Quercus_robur.jpg"],
    ["Rudbeckia hirta", "black-eyed susan", "Rudbeckia_hirta.jpg"],
    [
      "Rudbeckia hirta var. pulcherrima",
      "black-eyed susan",
      "Rudbeckia_hirta.jpg"
    ],
    [
      "Rudbeckia hirta 'Denver Daisy'",
      "black-eyed susan",
      "Rudbeckia_hirta.jpg"
    ],
    ["Acanthus mollis", "common bear's breech,bear's breeches", "NULL"],
    ["Marchantia polymorpha", "liverwort", "NULL"],
    ["Equisetum arvense", "common horsetail", "NULL"],
    ["Sequoia gigantea", "giant redwood", "NULL"],
    ["Cycas revoluta", "japanese sago plant", "NULL"],
    ["Phalaenopsis schilleriana", "schiller's moth orchid", "NULL"],
    ["Phaseolus vulgaris", "common bean,french bean", "NULL"],
    [
      "Fritillaria  meleagris",
      "snake's head fritillary,chequered lily",
      "NULL"
    ],
    [
      "Magnolia grandiflora",
      "evergreen magnolia,large-flowered magnolia",
      "NULL"
    ],
    ["Hosta plantaginea", "fragrant plantain lily", "NULL"],
    ["Rosa gallica", "gallic rose,french rose,rose of provins", "NULL"],
    ["Hedera helix", "common ivy", "NULL"],
    ["Senecio vulgaris", "birdseed,groundsel", "NULL"],
    ["Stellaria media", "common chickweed", "NULL"],
    ["Cardamine hirsuta", "hairy bittercress,lamb's cress", "NULL"],
    ["Fagus sylvatica", "common beech", "NULL"],
    ["Capsella bursa-pastoris", "shepard's purse,witches pouches", "NULL"],
    ["Calendula officinalis", "common marigold,pot marigold", "NULL"],
    ["Nigella damascena", "love-in-a-mist", "NULL"],
    ["Lamium purpurea", "french nettle,red deadnettle", "NULL"],
    ["Euphorbia helioscopa", "sun spurge,cat's milk", "NULL"],
    ["Matricaria perforata", "false chamomile", "NULL"],
    ["Sonchus asper", "prickly sowthistle", "NULL"],
    ["Alcea rosea", "hollyhock", "NULL"],
    ["Dianthus barbatus", "sweet william", "NULL"],
    ["Daucus carota", "wild carrot", "NULL"],
    ["Beta vulgaris", "common beet", "NULL"],
    ["Dipsacus fullonum", "common teasel,barber's brushes", "NULL"],
    ["Erysimum cheiri", "common wallflower,bleeding heart", "NULL"],
    [
      "Senecio jacobaea",
      "common ragwort,binweed,ragweed,stinking willy,st james's wort",
      "NULL"
    ],
    ["Circium vulagre", "spear thistle", "NULL"],
    ["Arctium minus", "lesser burdock", "NULL"],
    ["Taraxacum officianales", "dandelion,pee in the bed", "NULL"],
    ["Rubus fruticosus", "blackberry,bramble", "NULL"],
    ["Fraxinus excelsior", "common ash", "NULL"],
    ["Acer pseudoplatanus", "sycamore", "NULL"],
    ["Eschscholzia californica", "californian poppy", "NULL"],
    ["Centaurea cyanus", "cornflower", "NULL"],
    ["Lathyrus odoratus", "sweet pea", "NULL"],
    ["Limnanthes douglasii", "poached-egg plant", "NULL"],
    ["Cucurbita pepo", "marrow pumpkin,marrow,courgette", "NULL"],
    ["Ageratum altissimum", "white snakeroot", "NULL"],
    ["Cosmos bipinnatus 'Daydream'", "cosmea daydream", "NULL"],
    ["Coleus scutellarioides", "painted nettle", "NULL"],
    ["Myrtus communis", "common myrtle", "NULL"],
    ["Prunus laurocerasus", "cherry laurel", "NULL"],
    ["Philadelphus coronarius", "common mock orange", "NULL"],
    ["Berberis thunbergii", "japanese barberry", "NULL"],
    ["Euonymous japonicus", "evergreen spindle", "NULL"],
    ["Pinus sylvestris", "scots pine", "NULL"],
    ["Cotoneaster bullatus", "hollyberry cotoneaster", "NULL"],
    ["Allium giganteum", "giant onion", "NULL"],
    ["Coriandrum sativum", "coriander,chinese parsley,cilantro", "NULL"],
    ["Sambucus negra", "common elder", "NULL"],
    ["Myosotis sylvatica", "garden forget-me-not", "NULL"],
    ["Syringa vulgaris", "common lilac", "NULL"],
    ["Helianthus annuus", "common sunflower", "NULL"],
    ["Phlomis fruiticosa", "jerusalem sage", "NULL"],
    ["Pisum sativum", "garden pea", "NULL"],
    ["papaver somniforum", "opium poppy", "NULL"],
    ["Aquelegia vulgaris", "common columbine,granny's bonnets", "NULL"],
    ["Acer campestre", "field maple", "NULL"],
    ["Juglans regia", "common walnut", "NULL"],
    ["Sorbus acuparia", "rowan,mountain ash", "NULL"],
    ["Aesculus hippocastanum", "horse chestnut", "NULL"],
    ["Enkianthus campanulatus", "redvein enkianthus", "NULL"]
]
